### ISSUE TITLE
Example container chart app fails to render after initial load

### ISSUE THREAD

**Issue by markhealey** [OpenF2/F2#100]
Caused by [Highcharts error 16](http://www.highcharts.com/errors/16). Steps to reproduce:

* Clear localStorage cache for apps `F2.Storage.removeItem('requestedApps')` in your console
* Load example container
* Press 'Select Apps' and choose Price Movement Chart
* Press Save
* Chart should load fine
* Then press 'Select Apps' again and choose something else 
* Press Save
* Chart should fail to load and console should error on highcharts 16.

**Comment by qrider** [comment]
This appears to have been fixed. Chart loads fine after going through the steps above. Tested in IE11, FF, and Chrome.
