### ISSUE TITLE
Manifest loading is single-threaded

### ISSUE THREAD

**Issue by ilinkuo** [OpenF2/F2#113]
BUG

In https://github.com/OpenF2/F2/blob/master/sdk/src/container.js, there are comments

> // if an app is being loaded more than once on the page, there is the
> // potential that the jsonp callback will be clobbered if the request
> // for the AppManifest for the app comes back at the same time as
> // another request for the same app.  We'll create a callbackStack
> // that will ensure that requests for the same app are loaded in order
> // rather than at the same time

and 

> // loop through each item in the callback stack and make the request
> // for the AppManifest. When the request is complete, pop the next 
> // request off the stack and make the request.

If you examine the associated code, its solution to the collision problem is to effectively single-thread the manifest requests, as only a single ajax request is active at any time. The next request is only initiated by the <code>completeFunc()</code>. That is a very wrong way to solve the collision problem.

**Comment by AndyJepkes** [comment]
Has anyone developed an extension or found a workable solution for this problem? I'm trying to avoid the single-thread approach.

**Comment by ecirmada** [comment]
Can we have a CORS alternative?

**Comment by brianbaker** [comment]
JSON/CORS can be configured as long as the container developer and app developers work together to make the necessary configuration (headers/auth) so that it will work.  The container developer would need to override `xhr` in order to force JSON/CORS.
