### ISSUE TITLE
Enhancement: F2 view 

### ISSUE THREAD

**Issue by ilinkuo** [OpenF2/F2#136]
Enhancement 1: f2-view-param to handle view transitions

F2 views are currently handled via simple replacement. There is a need for more complicated transitions. This would ideally be handled in a declarative fashion similar to the current data-f2-view and data-f2-app-view-trigger. This proposal is for a backwards-compatible API change to accommodate this concern.
- Add an optional data-view-param attribute
- The value of the of the param is a JSON object of the form {'transition': 'flip'}
- _initAppEvents JSON.parse() the param and invokes <code>appConfig.ui.Views.change(view, param);</code>
- The change() dispatch code uses the value of transition to dispatch to a custom handler. The handlers could be preregistered _by the container_ via something like `F2.Views.register( viewName, handler)`

Example values of transition are 'flip', 'dropdown', 'slide', etc. -- basically, anything that you might find in a powerpoint effect.

**Comment by brianbaker** [comment]
Views were a rarely used feature of v1 that will be dropped in v2.
