### ISSUE TITLE
Switch CDN provider from cdnjs to jsdelivr?

### ISSUE THREAD

**Issue by markhealey** [OpenF2/F2#148]
It was suggested (via [email](mailto:info@openf2.org)) F2 javascript files get moved to [jsdelivr](http://www.jsdelivr.com/) from [cdnjs](http://cdnjs.com/) for better overall support in addition to a bigger network footprint and higher uptime. In case you aren't aware, F2 [introduced CDN support](http://blog.openf2.org/2013/09/f2-now-on-cdnjs.html) in September 2013.

I'd like to open the poll for voting on the issue. Looking at [this uptime chart](http://www.cdnperf.com/) jsdelivr outperforms cdnjs.

Comment with `cdnjs` or `jsdelivr` to cast your vote.

Thanks.

**Comment by ricardopolo** [comment]
And today CDNJs is faster than JSDelivr
http://www.cdnperf.com/
