### ISSUE TITLE
HTML Templates instead of inline html in JS

### ISSUE THREAD

**Issue by raunakkathuria** [OpenF2/F2#165]
As of now we have to define all the html in the manifest.js (can you explain if possible why this implementation was favored) 

![screen shot 2014-04-21 at 8 14 14 pm](https://cloud.githubusercontent.com/assets/2534747/2754200/816694c2-c94e-11e3-9a3e-ebb0a13e9396.png)

Is there any other way like creating html templates and referring them the way we refer css/js i.e. by specifying the url like this

![screen shot 2014-04-21 at 8 17 06 pm](https://cloud.githubusercontent.com/assets/2534747/2754215/e93a8432-c94e-11e3-83b8-0b8697062233.png)

I think it will separate out the structure and will help in modularity.

**Comment by SViradiya-Fintech** [comment]
hi we are using openf2 with multiple  financial apps, it is around 35 apps., we use javascript framework,
we have html, manifiest js, and appclass js.  so when ever we do some design releated changes in html, we have to minify html and put it in manifiest file. some time during copy paste, we wrongly copy paste in other application folder
