### ISSUE TITLE
Add option to send withCredentials property in F2 XHR

### ISSUE THREAD

**Issue by markhealey** [OpenF2/F2#170]
We recently discovered that when sending cross-domain ajax requests, the XHR object does not automatically include the relevant cookies for the target domain. This caused an issue for some hosting the F2 container on one domain and using a session cookie to authenticate the F2 app request from another domain. 

An addition to add the `withCredentials` property to the F2 XHR object has been proposed. This property defaults to `false` and is standard on `XMLHTTPRequest` as [shown here](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#Properties). 

It's difficult for Container Developers to enable this flag in F2 today because they're required to [override](http://docs.openf2.org/container-development.html#override-the-appmanifest-request) the _entire_ F2 AppManifest XHR request for a simple property addition. 

It is likely we'll add this to the [`ContainerConfig`](http://docs.openf2.org/sdk/classes/F2.ContainerConfig.html) provided to `F2.init()`.

**Comment by brianbaker** [comment]
in practice most F2 implementations end up overriding XHR in order to hook in authentication and at that point in time can and do specify `withCredentials`.
