### ISSUE TITLE
App Batch Requests -- Grouping

### ISSUE THREAD

**Issue by timburcham** [OpenF2/F2#177]
I've received a request related to app batch requests, and having the ability to specify grouping of batches.

There is a need to alter the behavior of the grouping functionality currently spec'd in F2. The current behavior is batch or no batch, nothing in between.

Request that the framework is updated to simply support a list of groups vs only allowing the one group. So in the app config, provide a list of group id's and then reference the group id's as an additional parameter to support multiple groupings.

Would love to know LOE to add this to the spec.

**Comment by markhealey** [comment]
There has been no additional conversation on this since Oct. and @zackferraro's fiddle demonstrates how to make it work.
