### ISSUE TITLE
Extract "bootstrap-modal" code into a plugin

### ISSUE THREAD

**Issue by montlebalm** [OpenF2/F2#209]
As an F2 developer, I'd like to remove the "bootstrap-modal" code from the core library, so I can remove the dependency on jQuery (Issue #39).

I haven't dug into it, but my gut feeling is that we can pull out the UI code around modals and put it an F2 plugin. This would be a great opportunity to create a real plugin and simplify the core lib at the same time.

**Comment by brianbaker** [comment]
`F2.UI` is no more for v2.
