### ISSUE TITLE
Remove dependency on easyXDM

### ISSUE THREAD

**Issue by montlebalm** [OpenF2/F2#210]
As an F2 developer, I'd like to remove the dependency on easyXDM to reduce the number of custom packages I have to support.

easyXDM is a large library and my impression is that it's not widely used by consumers of F2. I don't know if it's possible to put this functionality in a plugin, but it would be a big win to pull this out.

Do we know who is using secure apps? Does anyone want to try and extract secure apps into a plugin?

**Comment by qrider** [comment]
I'm assuming we can move to [cross-document messaging](https://html.spec.whatwg.org/multipage/comms.html#crossDocumentMessages) for this. [CDM support for iframes is IE8 and above.](http://caniuse.com/#feat=x-doc-messaging)
