### ISSUE TITLE
Deprecate `F2.isLocalRequest`

### ISSUE THREAD

**Issue by montlebalm** [OpenF2/F2#214]
As an F2 developer, I want to depreciate `F2.isLocalRequest` because I want F2 to contain only methods relevant to consumers.

Is `F2.isLocalRequest` useful enough to be attached to the core library? F2 is perched between being a general convenience library and a specialized app integration library. My preference is to move F2 away from the former and more solidly into the latter category.

**Comment by brianbaker** [comment]
this is pretty heavily used as a part of the XHR config that @markhealey mentioned so we'll leave it in the API
