### ISSUE TITLE
Depreciate `F2.isNativeDOMNode`

### ISSUE THREAD

**Issue by montlebalm** [OpenF2/F2#215]
As an F2 developer, I want to depreciate `F2.isNativeDOMNode` because I want F2 to contain only methods relevant to consumers.

Similar to #214, `F2.isNativeDOMNode` feels like a helper function that got added to the main API. I don't think it supports F2's goal of being a web integration library.

**Comment by qrider** [comment]
I am inclined with Mark on this. Let's make this private. It is a helper function and is pervasive throughout the code. One thing that it does well is enable us to notify the consumer if an invalid node is passed.

Locations this function is used:
- appRender
- _createHandler
- _isPlaceholderElement
- _loadHtml
- _loadSecureApp
- loadPlaceholders
- registerApps
