### ISSUE TITLE
Add log message when using depreciated features

### ISSUE THREAD

**Issue by montlebalm** [OpenF2/F2#225]
"As a developer using F2, I'd like the library to tell me when I'm using a depreciated feature."

Would it be helpful to add a `console.log` message whenever someone uses a depreciated feature? The user would never see it and it would alert the developer that they need to transition to an alternative.

**Comment by markhealey** [comment]
:+1: I like it

**Comment by brianbaker** [comment]
any deprecated functionality is getting pulled in v2
