### ISSUE TITLE
Remove compiled files from project

### ISSUE THREAD

**Issue by montlebalm** [OpenF2/F2#230]
Including the compiled documentation and library obscures commits to the project by making it harder to isolate changes.

I propose hosting the built "F2.js" files on OpenF2.org with a link to current and previous versions. This will make it more clear what users are getting and will potentially drive more traffic to the site.

**Comment by brianbaker** [comment]
We probably don't want to host the files direct from openf2.org but rather link over to cdnjs?

**Comment by montlebalm** [comment]
I was thinking merely of hosting it for the download link, but it's good to think about what would happen if users started including it on live pages. Leaving it on cdnjs for the time being works for me.

**Comment by markhealey** [comment]
:+1:  for cdnjs
