### ISSUE TITLE
"Easy Mode" app loading with script tag?

### ISSUE THREAD

**Issue by montlebalm** [OpenF2/F2#231]
Would it be beneficial to have a way to include F2 apps by dropping a single `<script>` tag? It could be convenient in use cases where there's a single app that doesn't need to communicate with the page or other apps.

Twitter and Facebook use similar patterns with success, because they're largely isolated from the other elements of the page.

We'd probably have to have a "link generator" that would accept the AppConfig and spit out a single url. You'd take that url and paste it on the page where you wanted the app to appear.

**Comment by markhealey** [comment]
This has come up in numerous conversations over the past few years. It'd be useful for quick wins but given the amount of customizations we've seen over time, I'm not sure how many firms would actually use it.

**Comment by brianbaker** [comment]
How does this differ from #169?

**Comment by montlebalm** [comment]
Its impact is less significant with placeholders, but it removes the need to know anything about F2 to include an app. It might help ease the adoption of F2 by more casual audiences. It's a fair point that we might be better served by improving placeholders.

**Comment by qrider** [comment]
I have had clients successfully use a placeholder and have loved it. Makes the integration and learning curve really easy.

**Comment by markhealey** [comment]
Going to close this in favor work done in #169 and the new [App Placeholder](http://docs.openf2.org/container-development.html#auto-loading-apps) functionality.
