### ISSUE TITLE
F2 Script Error When Using With jQuery In No Conflict Mode

### ISSUE THREAD

**Issue by smoderski** [OpenF2/F2#232]
F2.basic.js Uncaught TypeError: $ is not a function line 4124

When running F2 with jQuery in no conflict mode, there is an error being thrown on line 4124 in F2.basic.js.  The jQuery reference should be changed from $(root) to jQuery(root).

**Comment by markhealey** [comment]
Thanks @smoderski, this can be addressed in 1.4 #142

**Comment by brianbaker** [comment]
Looks like in 1.4-wip this line of code no longer exists due to refactoring, but there are a few instances of `$` that need to be changed to `jQuery`.
