### ISSUE TITLE
Unable to install via npm due to preinstall requiring root access

### ISSUE THREAD

**Issue by pornel** [OpenF2/F2#235]
package.json contains:

	"scripts": {
		"preinstall": "npm install grunt-cli markitdown -g"
	},

Global installation requires root privileges, and that's quite problematic for us, e.g. our CI servers don't allow it.

Could you move these packages to (dev)dependencies and use `npm bin` (`./node_modules/.bin`) instead?

**Comment by markhealey** [comment]
@pornel that was missed in our just-released v1.4.0. We replaced markitdown as part of #142. We'll get that `preinstall` cleaned up...

**Comment by markhealey** [comment]
@brianbaker please review and merge? Thanks.

**Comment by qrider** [comment]
preinstall has been removed from package.json in 1.4.1-wip
