### ISSUE TITLE
1.4 not on cdnjs yet

### ISSUE THREAD

**Issue by pornel** [OpenF2/F2#236]
The [documentation](http://docs.openf2.org/f2js-sdk.html#download) recommends using

    <script src="//cdnjs.cloudflare.com/ajax/libs/F2/1.4.0/f2.min.js"></script>

but the file isn't on the CDN yet: https://cdnjs.com/libraries/f2

**Comment by markhealey** [comment]
Strange. The cdnjs team merged it...

https://github.com/cdnjs/cdnjs/pull/4536

We'll take a look.

**Comment by markhealey** [comment]
Linking to #234

**Comment by markhealey** [comment]
It's up now...

https://cdnjs.cloudflare.com/ajax/libs/F2/1.4.0/f2.js
