### ISSUE TITLE
Documentation: backslash escaping in HTML

### ISSUE THREAD

**Issue by pornel** [OpenF2/F2#251]
http://docs.openf2.org/container-development.html#other-options suggests:

```html
data-f2-context="{\"hello\":\"world\"}"
```

However, HTML doesn't use backslashes for escaping, only entities.

**Comment by markhealey** [comment]
Thanks, @pornel would you be willing to make this change in the [source](https://github.com/OpenF2/F2/blob/master/docs/src/container-development.md#other-options) and submit a PR to `1.4.1-wip` (#249)?
