### ISSUE TITLE
Add Containers to F2 after Initialization

### ISSUE THREAD

**Issue by ghost** [OpenF2/F2#256]
Background : We have an ajax call which will make F2 call, currently we have two F2 calls , by the time page loads. the order of F2 is loosing.

Is there a way to add containers to F2 after initialization !

Just to ellaborate. for ex : if I have two F2 Apps on a Page.

1. Without Ajax Call 2. Without Ajax call.

By the time the page loads there are possibilities that any of them will load.. and there is order being messed up.

so if they a way to add an App to a container after initialization ?

Thanks,
Sudheer.

**Comment by qrider** [comment]
So you want to make 2 synchronous F2 calls so that the second app only loads after the first app? 
Can you provide a [Plunker ](http://plnkr.co/) or JsFiddle?

**Comment by qrider** [comment]
Closing. No response. Will reopen if the question surfaces again.
