### ISSUE TITLE
GET NEW QUOTE button in the Quote app example doesn't work

### ISSUE THREAD

**Issue by ryanolsen** [OpenF2/F2#257]
When I click the "GET NEW QUOTE" button in the Quote app example I would expect it to load a new quote. Right now nothing happens.

/examples/apps/JavaScript/Quote/appclass.js

**Comment by markhealey** [comment]
This is the same issue as https://github.com/OpenF2/iOS-Container/issues/5.

I think the "Get new quote" button wasn't completely wired up. That text input is supposed to have an autocomplete (see [openf2.org/examples](http://www.openf2.org/examples) and type in "MSFT").

The iPad app loads the _same_ App from [openf2.org/examples](http://www.openf2.org/examples), so fixing the App on the website's Examples page will resolve https://github.com/OpenF2/iOS-Container/issues/5. It is a separate App (same JS code though) as the one in the Github repo mentioned by @ryanolsen above.

**Comment by timburcham** [comment]
@ryanolsen : could you verify?

**Comment by qrider** [comment]
I have verified fix. Closing
