### ISSUE TITLE
Documentation is missing CSS

### ISSUE THREAD

**Issue by tburcham** [OpenF2/F2#261]
http://docs.openf2.org/container-development.html
 This file is getting a 404 error: http://www.openf2.org/2.2.3/css/site.css​

**Comment by tburcham** [comment]
Note that this is due to a recent version bump on the primary F2 website to v2.2.5.  Docs simply need to be updated to reflect this, anywhere the version is hardcoded.

**Comment by timburcham** [comment]
@markhealey What, if anything, is required for changes like this to be reflected https://docs.openf2.org?  This doesn't look like Jekyll is running anything.

**Comment by markhealey** [comment]
@tburcham Just commit the changes to `gh-pages` and github does the rest.

**Comment by timburcham** [comment]
Fixed via https://github.com/OpenF2/F2/commit/26211fc9b7729c153086911b2da4d0ec7256e24c
