### ISSUE TITLE
Incorrect Version Number in basic.js

### ISSUE THREAD

**Issue by christoferpeterson** [OpenF2/F2#263]
According to the comment from https://raw.githubusercontent.com/OpenF2/F2/master/sdk/packages/f2.basic.js

    /*!
    * F2 v1.4.0 01-23-2014
    * Copyright (c) 2014 Markit On Demand, Inc. http://www.openf2.org

But according to the code

    /** 
     * Function to get the F2 version number
     * @method version
     * @return {string} F2 version number
     */
    version: function() { return '1.3.3'; }

**Comment by qrider** [comment]
This was fixed in version 1.4.1
