### ISSUE TITLE
F2 App Class Script not working in IE 9

### ISSUE THREAD

**Issue by g-sudheer** [OpenF2/F2#264]
Hi ,

      F2.Apps["org_abc_xyz_offer"] = (function() {
      
       var redirectUrl;
       var app = function(appConfig, appContent, root) {
          
             this.redirect = appContent.data.redirect;
             redirectUrl = this.redirect;

             F2.log(' redirecting to : '+this.redirect);
       }
       
       app.prototype.init = function() {

             if(null !== redirectUrl && typeof redirectUrl !== "undefined"){
             window.top.location=redirectUrl;
             }
       }
       return app;
       
      })();

Above script is the simple script I have , its not working only in IE - 9 apart from that its working in Chrome and FireFox.

Please advice !!

Thanks,
Sudheer.

**Comment by brianbaker** [comment]
Does IE give out any script errors?  Or the code just doesn't execute?

**Comment by g-sudheer** [comment]
There were no errors, just the code doesn't execute...I was using 1.4.0 version where is problem is coming, when I tried to use 1.3.3 its working perfect.

**Comment by brianbaker** [comment]
Do you happen to have a jsfiddle you could share to reproduce?

**Comment by g-sudheer** [comment]
I was able to try and was able to figure out the solution.

Just I have one question.

If I have two or three or four F2 Apps on the same page (not a batchrequest)

When I do F2.init() and F2.registerApps(appConfig)  all apps will be registered at once.

How can I register one single app after the other ?

Thanks,
Sudheer.

**Comment by brianbaker** [comment]
You can either call `F2.registerApps()` multiple times (one for each app) or if you want to guarantee that one app completely loads before the next app you'll need to utilize the [AppHandlers](http://docs.openf2.org/container-development.html#apphandlers-for-app-layout) events, probably one like [APP_RENDER_AFTER](http://docs.openf2.org/sdk/classes/F2.Constants.AppHandlers.html#property_APP_RENDER_AFTER) in order to wait until each app has loaded before moving to the next one.

**Comment by brianbaker** [comment]
So, to confirm - you were able to solve this one in your own code and there is no potential bug in F2 for this issue?

**Comment by g-sudheer** [comment]
Sorry for the delay !! Yes Please...

**Comment by brianbaker** [comment]
Closing issue as this appears to not be an F2 issue.  Will reopen if found otherwise.
