### ISSUE TITLE
F2 Init() Initialization

### ISSUE THREAD

**Issue by g-sudheer** [OpenF2/F2#268]
Hi ,

I have few F2 App on a page, Some on header ,some on body and some on footer.
I have both 'GET' and 'POST' app also among them.
When the page loads , the apps on the header is getting initialized. when comes to page or body since the app is already initialized its not initialized further and problem coming with registering them.

Is there a way to initialize to make sure all app are loaded and then initialize and then register.

FYI - I'm checking all the time F2.isInit() also.

Thanks,
Sudheer.

**Comment by christoferpeterson** [comment]
Hello Sudheer,

I am not sure I understand the issue you are describing. Are you calling F2.registerApps() and passing all the apps you want to register? The typical pattern is to register the apps and when F2 pulls the apps in, it will then initialize the apps after they have loaded. The flow would go Register App > F2 Loads App > F2 Initializes app class.

Hope this helps,

Christofer Peterson

**Comment by timburcham** [comment]
It might be helpful to get a Gist or JsFiddle of a simple example for the issue, Sudheer, so that the team can see what's happening.

**Comment by g-sudheer** [comment]
Sure, I will make one JS Fiddle and share you. Is there a way to prioritize F2.Init() ?

**Comment by christoferpeterson** [comment]
A JsFiddle will help with my understanding of your issue. Until then, I am not sure I can give a satisfactory answer to your question.

**Comment by qrider** [comment]
Closing. No Response.
