### ISSUE TITLE
How to use F2 Registry and Store

### ISSUE THREAD

**Issue by VivekPMenon** [OpenF2/F2#269]
I have been navigating around the F2 documentations for a while to get more detailed information regarding **F2 App deployment and Discovery**. Can someone please help me here?

1.   How can I add AppId and Manifest to the public F2 registry? I can see the sample is using http://www.openf2.org/F2/registry api to get the app manifest. I tried to POST requests to the API but doesn't seem to create any new resource. Recommendation is to create and maintain Service Registry by the Organization themselves (for privacy reasons like mentioned in the F2 blogs)?

2.   The only feature available in F2 Developer Center (https://developer.openf2.org/) right now is  creating AppId? website says app management can also be done. But I couldn't find it.

3.  Documentation talks briefly about store, but couldn't get information on how that can be utilized. Is there any further documentation on this?

**Comment by timburcham** [comment]
Hi Vivek, I'll address each of your questions individually, but first, should outline the state of F2 Registry, which will help.

The notion of a registry of apps existing is documented in the F2 site, as you mentioned.  However, this is simply a reference example.  There is not a centralized F2 registry or store, and as the Advisory Board took a look at this problem, found that there is not currently a need for a centralized registry, but rather, a decentralized network of registries.  We cover a lot of the thinking on this on the [blog](http://blog.openf2.org/2015/08/f2-registry-organizing-and-connecting.html).  This concept of F2 Registry, a specification for how it should exist, etc, is the next project we have launched with F2, and we are currently looking for contributors to this effort.  With the formation of our Technical Steering Committee, you should see more momentum on this in the near future.

Back to your questions:
1) The recommendation is that the organization themselves provides a registry that approximates the reference example. This could later be brought in to the larger registry.

2) This concept of the F2 Developer Center was not progressed from what you read.  If you would be interested in helping further develop this concept, let us know, and we can get you more involved.

3) See above.

Hopefully that helps?

Tim

**Comment by VivekPMenon** [comment]
Thanks much for the explanation. It helps.
