### ISSUE TITLE
Issue related to i-pad  -  Set description as 'Tube'. 

### ISSUE THREAD

**Issue by SSathwara-TBA** [OpenF2/F2#280]
Failed Scenario 
==========

My manifest.js contents is as below

F2_jsonpCallback_152({
    //"scripts": [
	//	config.clientUrl + "/Products/VCM/152/appclass.js"
    //],
    //"styles": [
    //     config.clientUrl + "/Products/VCM/152/app.css"
    //],
    "apps": [{
        "data": {},
        "html": ['<div>Test</div>'].join("")
    }]
})

I have modified the jsfiddle code for sample 

http://jsfiddle.net/ssathwara/eBqmn/17/ 

Modified the _appConfig parameters  as per the screen shot 

When I have run the code from the web browsers (Chrome,mozila and safari )  then it will shows the oupput as per the below  screenshot.

Web-browser output 
-----------------------
![webbrowser_output](https://cloud.githubusercontent.com/assets/19744052/17480695/be6396fc-5d96-11e6-8b44-983ceec8eb56.png)

Same Url run from the i-pad then it will shows output as per below screens shot. (I am not able see any output )

i-pad output 
---------------

![i-pad_output](https://cloud.githubusercontent.com/assets/19744052/17480984/4d0b5e52-5d98-11e6-9f61-b399f8ae9034.jpg)

When I have modified the description,name,appType,appMode and appName fields with the 'Tub/e' then it will shows output as below in web-browser  and i-pad .

Web-browser output 
-----------------------
![webbrowser_output1](https://cloud.githubusercontent.com/assets/19744052/17481133/f8014952-5d98-11e6-906e-3a1d04719b9c.png)

i-pad output 
---------------
![i-pad_output1](https://cloud.githubusercontent.com/assets/19744052/17481159/27def584-5d99-11e6-9016-1bfb7e551018.jpg)

For your ready reference i have shared fiddle link 

If you required any other details let me know.

**Comment by qrider** [comment]
Thanks @SSathwara-TBA. I will have a look this week.

**Comment by qrider** [comment]
From what I can tell your server is no longer available. closing.
