### ISSUE TITLE
Add Failure AppHandler constants

### ISSUE THREAD

**Issue by ZebLawrence** [OpenF2/F2#281]
It could be useful to have more "fail" app handler constants other than the "appScriptLoadFailed". So a container developer can gracefully handle other fail events such as AppManifest request.

I would like to add the APP_MANIFEST_REQUEST_FAIL handler that will get triggered when the request for the app manifest triggers the error callback. This way in the event that the 3rd party app provider endpoint is down or returning an error for some reason the consumer would have the ability to display a message or placeholder app rather than having a blank spot in the page where the app was expected to be.

**Comment by brianbaker** [comment]
fixed by #283
