### ISSUE TITLE
How to Use f2-autoload on F2.Event.emit or F2.Event.on

### ISSUE THREAD

**Issue by g-sudheer** [OpenF2/F2#288]
Hi,

There is a client app which emits an event (uses F2.Events.emit) , based on the event I would like to setup a container and would like to use f2-autoload.

Could you please provide an example on how to use that ?

Thanks,
Sudheer.

**Comment by jatintyagi** [comment]
you would have to load your F2 app inside your F2.Events.on("EventName",function(data){})  

 var _token = F2.AppHandlers.getToken();
  //create & assign a "root" element for the App
  F2.AppHandlers.on(
    _token,
    F2.Constants.AppHandlers.APP_CREATE_ROOT,
    function(appConfig) {
		appConfig.root = document.getElementById(appConfig.appId); // Your container

    }
  );
  //render the App
  F2.AppHandlers.on(
    _token,
    F2.Constants.AppHandlers.APP_RENDER,
    function(appConfig, appHtml) {
      $(appConfig.root).append(appHtml); // appending HTML result
    }
  );
  //init F2 & register Apps
  F2.init();
  F2.registerApps([
    {
      appId: 'com_openf2_examples_nodejs_helloworld',
      manifestUrl: 'http://www.openf2.org/F2/apps'
    },
    {
      appId: 'com_openf2_examples_csharp_marketnews',
      manifestUrl: 'http://www.openf2.org/F2/apps'
    }
  ]);

**Comment by g-sudheer** [comment]
@jatintyagi , thank you for sharing this one.

I was aware of the above approach, but thank you for sending this.

I'm more looking with the new declarative approach on f2-autoload (http://docs.openf2.org/container-development.html#auto-loading-apps) using F2.Events.

something like..

<div id="F2.Events.on('xx' , loadF2) ? f2-autoload : 'app-id'" data-app-id="' data-manifesturl="http://test.f2.app"></div>



Thanks,
Sudheer.

**Comment by drawluap** [comment]
@g-sudheer, here's a basic example of the declarative approach in action from the documentation link that you provided:

http://jsfiddle.net/drawluap/jcpbthu8/

In terms of context passing between apps and container (via `F2.Events`), I don't that much changes  if a container developer opts to use the declarative approach. Specifically, the app class would still emit and listen for events and the container would also need to emit/listen if applicable. The declarative approach really only simplifies app registration but does not allow for declarative eventing (as far as I can tell).

I think you
