### ISSUE TITLE
Can't recieve event in secure app

### ISSUE THREAD

**Issue by vnabatov** [OpenF2/F2#291]
if isSecure is true

```
//F2-examples\examples\apps\JavaScript\CompareTool\appclass.js

F2.Events.on(
    "buy_stock", 
    function(data){
       console.log('get', data)        
    }
);
```
doesn't work 
(can't see get messages in console)
is it expected behavior?

[example](https://yadi.sk/d/nebjMqw73Mpat5)
if we set isSecure=false
F2-examples\examples\container\js\sampleApps.js:44
then it works
(can see get messages in console)

**Comment by brianbaker** [comment]
v2 will not support `isSecure`
