### ISSUE TITLE
Update Libraries w/ Known Security Vulnerabilities

### ISSUE THREAD

**Issue by qrider** [OpenF2/F2#295]
The following have been flagged to have known security vulnerability. 
- handlebars.js
- moment
- qs
- send
- UglifyJS2

As a user of F2 I would like to see the following libraries updated to stable versions. 
Presumably:
- handlebars ~> 4.0.0
- moment ~> 2.11.2
- qs ~> 1.0.0
- send ~> 0.11.1
- uglify-js ~> 2.6.0

**Comment by brianbaker** [comment]
fwiw these are devDependencies and nothing actually _in_ F2.

**Comment by pc2459** [comment]
Looking into this

**Comment by pc2459** [comment]
This should be closed, @qrider
