### ISSUE TITLE
Cannot pass DOM element references in event data

### ISSUE THREAD

**Issue by jsphstls** [OpenF2/F2#301]
Attempting to pass a DOM element reference, such as an event target, will result in this error:
Uncaught TypeError: 'Converting circular structure to JSON'

This is because all event data is stringified:
https://github.com/OpenF2/F2/blob/master/sdk/src/rpc.js#L238

F2 is supposed stringify only if there are actual sockets (iframes) to send to. In this case it is needlessly stringifying.

**Comment by brianbaker** [comment]
rpc is going away for v2
