### ISSUE TITLE
Clarification of App HTML structure and division of responsibilities (for Container writers)

### ISSUE THREAD

**Issue by ilinkuo** [OpenF2/F2#86]
Clarification.

From reading the F2 docs and code, the diagram below is my understanding of what an archetypal F2 HTML structure is like. While I have gone beyond what F2 has proscribed in some places (notably the panels to the left and right of the central app content and the footer panel), please verify that what I have down is correct.

![f2-app-archetype](https://f.cloud.github.com/assets/1105240/431870/d5730d90-ae95-11e2-9250-1b3192b94fd0.png)

If this is correct, I'll follow up with some documentation/api clarification requests.

**Comment by brianbaker** [comment]
the examples page provides the ability to highlight the container (press `c`) or apps (press `a`).
