### ISSUE TITLE
Is it possible to display multiple F2 views?

### ISSUE THREAD

**Issue by ivanovergard** [OpenF2/F2#89]
Does APP_VIEW_TRIGGER always assume only a single view is visible at a time?  I'm working on an application where our “settings” view is more of an overlay than a single view, and it might be necessary for changes in it to update the main app view in the background. Is it possible to do this while still treating this as an “F2 view”?  If not, does the ability to display an f2 view without hiding another seem like a useful feature, or am I misunderstanding the point of views?

**Comment by brianbaker** [comment]
Views are being removed in v2.
